#!/bin/bash

if [ $# -ne 0 ]; then

comp=($@)

else

comp=(rpi01 rpi02 rpi03 rpi04 rpi05 rpi06 rpi07 rpi08 rpi09 rpi10 rpi11 rpi12 rpi13 rpi14 rpi15 rpi16 rpi17 rpi18 rpimpw)

fi

for computer in ${comp[*]}
do
	ping -c 1 -w 1  $computer &>/dev/null
	        if [ $? -ne 1 ]; then
		echo $computer: alive;
		       else echo $computer: dead
                fi
done


